TRUNCATE TABLE gameobject_addon;
TRUNCATE TABLE gameobject_battleground;
TRUNCATE TABLE gameobject_involvedrelation;
TRUNCATE TABLE gameobject_loot_template;
TRUNCATE TABLE gameobject_questrelation;
TRUNCATE TABLE gameobject_spawn_entry ;
TRUNCATE TABLE gameobject_template_addon ;
TRUNCATE TABLE gameobject_template ;
TRUNCATE TABLE gameobject_zone ;
TRUNCATE TABLE gameobject ;
TRUNCATE TABLE spawn_group_entry ;
TRUNCATE TABLE spawn_group_formation ;
TRUNCATE TABLE spawn_group_linked_group ;
TRUNCATE TABLE spawn_group_spawn ;
TRUNCATE TABLE spawn_group_squad ;
TRUNCATE TABLE spawn_group;